// Editorial archetype content generated by AI for a watch collection.
// One record per collection seed — all watches in the collection share it via WatchEditorialLink.
// Generated offline (Ollama) and stored in DB; zero AI cost at runtime.
namespace backend.Models;

public class WatchEditorialContent
{
    public int Id { get; set; }

    // The watch whose specs drove generation (most complete specs in its collection)
    public int SeedWatchId { get; set; }
    public Watch SeedWatch { get; set; } = null!;

    public string WhyItMatters { get; set; } = "";
    public string CollectorAppeal { get; set; } = "";
    public string DesignLanguage { get; set; } = "";
    public string BestFor { get; set; } = "";

    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

    public ICollection<WatchEditorialLink> Links { get; set; } = [];
}
