--
-- PostgreSQL database dump
--

\restrict Ej7hikzplgFmFrzt604ilrSIClnxttPim3geSQng8xbPBirYTpE0lhysdvp7Ixo

-- Dumped from database version 17.9 (Debian 17.9-1.pgdg12+1)
-- Dumped by pg_dump version 17.9 (Debian 17.9-1.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: WatchEditorialContents; Type: TABLE; Schema: public; Owner: tourbillon
--

CREATE TABLE public."WatchEditorialContents" (
    "Id" integer NOT NULL,
    "SeedWatchId" integer NOT NULL,
    "WhyItMatters" text NOT NULL,
    "CollectorAppeal" text NOT NULL,
    "DesignLanguage" text NOT NULL,
    "BestFor" text NOT NULL,
    "GeneratedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."WatchEditorialContents" OWNER TO tourbillon;

--
-- Name: WatchEditorialContents_Id_seq; Type: SEQUENCE; Schema: public; Owner: tourbillon
--

ALTER TABLE public."WatchEditorialContents" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."WatchEditorialContents_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: WatchEditorialLinks; Type: TABLE; Schema: public; Owner: tourbillon
--

CREATE TABLE public."WatchEditorialLinks" (
    "WatchId" integer NOT NULL,
    "EditorialContentId" integer NOT NULL
);


ALTER TABLE public."WatchEditorialLinks" OWNER TO tourbillon;

--
-- Data for Name: WatchEditorialContents; Type: TABLE DATA; Schema: public; Owner: tourbillon
--

COPY public."WatchEditorialContents" ("Id", "SeedWatchId", "WhyItMatters", "CollectorAppeal", "DesignLanguage", "BestFor", "GeneratedAt") FROM stdin;
1	38	The Patrimony collection embodies Vacheron Constantin's dedication to timeless elegance and traditional watchmaking. This reference represents the pinnacle of understated sophistication, a testament to the brand's enduring legacy.	Highly sought after by discerning collectors who appreciate classic design and impeccable craftsmanship. Its limited production and strong resale value make it a coveted piece for serious horology enthusiasts.	The 85180/000J-H069 exudes understated refinement with its warm yellow gold case, meticulously finished dial, and harmonious proportions. The subtle interplay of textures and the choice of strap add a touch of personality without compromising its classic allure.	This watch is ideal for individuals who value timeless elegance and appreciate the finer details. It complements formal attire and adds a touch of sophistication to everyday wear. Its versatility makes it suitable for various occasions, from business meetings to evening events.	2026-03-22 03:42:40.694496+00
2	232	The Datejust embodies Rolex's enduring legacy of precision engineering and iconic design. Its evolution over decades reflects the brand's commitment to refining horological excellence while maintaining timeless appeal.	A perennial favorite among collectors, the Datejust enjoys strong resale value and consistent demand. Its versatility makes it a sought-after piece for both seasoned enthusiasts and those entering the world of luxury watches.	The M126200-0005 embodies classic Datejust elegance with its fluted bezel, Cyclops lens over the date window, and clean dial layout. The sunray blue dial adds a modern touch, while the Jubilee bracelet exudes sophistication.	This Datejust is ideal for individuals seeking a versatile timepiece that seamlessly transitions from formal occasions to everyday wear. Its 36mm size suits a range of wrist sizes and complements both tailored attire and casual ensembles.	2026-03-22 03:42:53.604369+00
3	239	The Submariner Date M126610LV-0002 represents Rolex's ability to evolve its iconic designs while maintaining their core essence. It honors the brand's diving heritage with a contemporary twist, solidifying its position as a leader in luxury sports watches.	This Submariner is highly sought after by collectors seeking a modern classic with strong resale value. Its limited production and enduring popularity often result in waitlists, making it a coveted piece for serious watch enthusiasts.	The M126610LV-0002 features a clean, functional design language with sharp lines and polished surfaces. The contrasting green bezel against the black dial creates a striking visual impact, while the 41mm Oystersteel case offers both durability and elegance.	This versatile timepiece is perfect for individuals who appreciate both style and functionality. It complements active lifestyles, formal occasions, and everyday wear, making it a suitable choice for those seeking a timeless and sophisticated watch.	2026-03-22 03:43:08.846201+00
4	313	The SLGW003 represents a pivotal moment for Grand Seiko, seamlessly blending its storied heritage of precision with the modern demands of discerning collectors. It showcases the brand's commitment to pushing horological boundaries while maintaining its signature elegance.	This timepiece is highly sought-after by serious watch enthusiasts who appreciate Grand Seiko's exceptional craftsmanship and innovative movements. Its limited production run and prestigious status ensure strong resale value and a place on many collectors' wishlists.	The SLGW003 embodies a minimalist aesthetic with sharp, angular lines that contrast beautifully with the smooth, flowing curves of its dial. The brilliant hard titanium case exudes both durability and sophistication, while the meticulously finished blue dial adds a touch of contemporary flair.	This watch is ideal for individuals who value understated luxury and appreciate the art of horology. Its versatility makes it suitable for both formal occasions and everyday wear, complementing a range of styles from classic to modern.	2026-03-22 03:43:23.383556+00
5	34	This Métiers d’Art Tribute to The Celestial - Scorpio embodies Vacheron Constantin's enduring dedication to the highest levels of artisanal craftsmanship. It stands as a testament to their mastery of guilloché, enamel work, and gem-setting, pushing the boundaries of horological artistry.	This boutique-exclusive timepiece is highly sought after by discerning collectors who appreciate exceptional craftsmanship and rare beauty. Its limited production run and intricate design ensure strong resale value and potential for future appreciation.	The dial is a mesmerizing canvas of hand-guilloché artistry, depicting the Scorpio constellation with meticulous detail. The blue enamel provides a rich backdrop for brilliant-cut diamonds marking key stars, while baguette-cut sapphires adorn the bezel, lugs, crown, and buckle, adding a touch of regal opulence.	This exquisite timepiece is perfect for collectors seeking a statement piece that transcends mere functionality. It's ideal for formal occasions, black-tie events, or any moment where one wishes to showcase their appreciation for the finest horological art.	2026-03-22 03:43:39.551791+00
6	249	The Day-Date has long been a symbol of Rolex's commitment to precision and elegance, worn by world leaders and discerning collectors alike. This reference embodies that legacy while subtly pushing boundaries with its contemporary Everose gold and chocolate dial combination.	A highly sought-after piece within the Rolex universe, the Day-Date 36 in Everose gold commands a premium price due to its limited availability and enduring desirability. Its resale value remains strong, reflecting its status as a timeless classic.	The watch adheres to the iconic Day-Date DNA: fluted bezel, President bracelet, and a clear dial layout. The warm Everose gold case and ombré chocolate dial with diamond accents introduce a softer, more sophisticated aesthetic, balancing tradition with contemporary flair.	This timepiece is perfect for formal occasions, black-tie events, or everyday wear by individuals who appreciate understated luxury and timeless design. Its versatility extends to pairing with both classic and modern attire.	2026-03-22 03:43:54.417846+00
7	324	The SBGH341 Sakura-Kakushi embodies Grand Seiko's dedication to seasonal artistry and meticulous craftsmanship. It stands as a testament to the brand's ability to capture fleeting beauty in horological form, pushing the boundaries of dial design with its subtle color shifts.	This limited edition timepiece will be highly sought after by collectors drawn to Grand Seiko's exceptional finishing and unique seasonal offerings. Its scarcity and exclusivity ensure strong resale value and potential for future appreciation.	The SBGH341 features a classic Grand Seiko aesthetic with a contemporary twist. The 38mm stainless steel case houses a pink dial that evokes the subtle hues of blooming sakura, while the intricate finishing details on the movement reflect the brand's commitment to precision and artistry.	This elegant timepiece is ideal for discerning individuals who appreciate understated luxury and sophisticated design. Its versatility makes it suitable for both formal occasions and everyday wear, complementing a variety of styles.	2026-03-22 03:44:08.842452+00
8	54	Vacheron Constantin's Overseas collection bridges the gap between traditional craftsmanship and modern design, and the 5520V/210R-B966 exemplifies this ethos. Its integrated chronograph movement is a testament to the brand's horological prowess, while its contemporary aesthetic resonates with today's discerning collector.	This watch appeals to collectors seeking both prestige and versatility. As an ultra-luxury timepiece from a respected maison, it holds strong resale value and often features on waitlists due to limited production. Its unique combination of pink gold and green dial creates a distinctive allure.	The 5520V/210R-B966 embodies a sophisticated yet sporty aesthetic. The 42.5mm pink gold case, with its integrated bracelet, exudes timeless elegance. The intense green dial adds a contemporary touch, while the chronograph subdials provide a dynamic visual counterpoint.	This watch is perfect for individuals who appreciate both luxury and functionality. Its versatility allows it to be worn on formal occasions or during everyday activities. It complements a variety of styles, from tailored suits to casual attire.	2026-03-22 03:44:25.790539+00
9	328	The SBGE255 showcases Grand Seiko's mastery of both mechanical precision and sporty design. It represents the brand's evolution beyond traditional dress watches, demonstrating their ability to create versatile timepieces for a modern clientele.	This model appeals to collectors seeking a blend of functionality and elegance. Its limited production and strong market demand often result in waitlists, making it a coveted piece for serious enthusiasts.	The SBGE255 embodies Grand Seiko's signature understated sophistication. The 40.5mm stainless steel case is both robust and refined, while the blue dial features clean lines and meticulous finishing details. Its GMT functionality adds practicality without compromising its aesthetic appeal.	This watch is ideal for individuals who appreciate a versatile timepiece that can seamlessly transition from professional settings to weekend adventures. It complements a variety of styles and suits wrists of average size.	2026-03-22 03:44:40.832308+00
10	139	The Lange 1 191.039 stands as a testament to A. Lange & Söhne's enduring commitment to innovation and horological excellence. It embodies the legacy of the original Lange 1, which redefined watchmaking with its groundbreaking asymmetric design and oversized date display, while simultaneously pushing the boundaries of contemporary aesthetics.	This timepiece is highly sought-after by discerning collectors who appreciate the pinnacle of German craftsmanship and timeless design. Its limited production runs and enduring popularity contribute to its strong resale value and often result in waiting lists for eager enthusiasts.	The Lange 1 191.039 exudes a refined elegance through its meticulously crafted 18-carat white gold case, measuring 38.5mm in diameter. The captivating blue dial features the signature off-center layout and oversized date window, creating a harmonious balance of asymmetry and precision.	This watch is perfect for individuals who value understated sophistication and appreciate the finer details of horological artistry. It complements formal attire with its timeless elegance and can also elevate casual ensembles with its subtle yet impactful presence.	2026-03-22 03:44:59.996621+00
11	141	The Saxonia Thin embodies A. Lange & Söhne's dedication to understated elegance and precision engineering. It represents a return to the core values of horology, prioritizing craftsmanship over ostentatious complications.	This model is highly sought after by collectors who appreciate classic design and exceptional finishing. Its limited production and prestigious heritage ensure strong resale value.	The Saxonia Thin 205.086 features a minimalist dial with applied Arabic numerals and slender hands, creating a sense of refined simplicity. The 41mm white gold case is impeccably finished, showcasing the brand's commitment to detail.	This timepiece is ideal for discerning individuals who value understated sophistication. It complements formal attire and adds a touch of elegance to everyday wear.	2026-03-22 03:45:13.946991+00
12	134	The Zeitwerk 140.032 embodies A. Lange & Söhne's commitment to pushing horological boundaries while honoring traditional craftsmanship. Its digital display is a testament to the brand's innovative spirit, yet it remains deeply rooted in the principles of precision and meticulous execution.	Highly sought-after by serious collectors drawn to its unique aesthetic and technical prowess. The Zeitwerk 140.032 commands a premium price and often features on waitlists due to its limited production runs.	The Zeitwerk 140.032 is defined by its bold, architectural dial featuring a jumping digital display that dominates the silvered surface. The use of warm pink gold adds a touch of elegance while maintaining the watch's assertive presence. 	Individuals who appreciate avant-garde design and mechanical complexity. It's ideal for formal occasions or those seeking a statement timepiece that transcends conventional aesthetics.	2026-03-22 03:45:31.046945+00
13	255	The Chronomètre Furtif CF embodies F.P. Journe's relentless pursuit of horological innovation within a sporty context. It challenges conventional notions of legibility and aesthetics, demonstrating the brand's commitment to pushing boundaries while maintaining exceptional craftsmanship.	A highly sought-after piece among serious watch collectors, the Chronomètre Furtif CF commands a premium price due to its limited production and unique design. Its scarcity and exclusivity contribute to its desirability on the secondary market, often fetching significantly above retail value.	The Chronomètre Furtif CF adopts a minimalist aesthetic with a monochromatic palette of anthracite dial and tantalum case. The absence of overt branding and subtle indices create an understated yet sophisticated aura. Its 42mm diameter strikes a balance between presence and wearability, while the manual-winding movement adds a touch of horological artistry.	This timepiece is ideal for discerning individuals who appreciate unconventional design and exceptional horology. It complements a contemporary lifestyle with its understated elegance, making it suitable for both formal occasions and casual outings.	2026-03-22 03:45:49.044317+00
14	43	Vacheron Constantin's Historiques collection resurrects iconic designs from its past, ensuring the legacy of horological innovation lives on. The American 1921 embodies this ethos, reimagining a vintage masterpiece with contemporary refinement, solidifying Vacheron Constantin's position as a guardian of watchmaking heritage.	This piece attracts discerning collectors who appreciate understated elegance and historical significance. Its limited production and strong resale value make it a coveted addition to any serious collection. The waitlist for this model reflects its desirability among enthusiasts seeking unique timepieces.	The 82035/000G-B735 embodies a refined driver-style layout, characterized by its asymmetrical arrangement of subdials and elongated hour markers. Crafted in lustrous white gold, the watch exudes sophistication with its crisp lines and silver-toned dial, creating a harmonious balance between vintage charm and contemporary elegance.	This timepiece is ideal for individuals who value understated luxury and appreciate horological craftsmanship. Its versatility makes it suitable for both formal occasions and everyday wear, complementing tailored attire and adding a touch of sophistication to any ensemble.	2026-03-22 03:46:09.084701+00
15	60	The Royal Oak Perpetual Calendar represents Audemars Piguet's mastery of both contemporary design and intricate complications. It embodies the brand's commitment to pushing horological boundaries while staying true to its iconic aesthetic.	This reference is highly sought after by serious watch collectors drawn to its blend of elegance, functionality, and exclusivity. Its limited production runs and strong resale value contribute to its desirability on the secondary market.	The 26674ST.OO.1320ST.01 adheres to the Royal Oak's signature octagonal bezel and integrated bracelet, but refines it with a clean, minimalist dial layout that prioritizes readability despite the complex perpetual calendar display. The blue dial adds a touch of contemporary sophistication.	This timepiece is ideal for discerning individuals who appreciate both horological excellence and timeless style. It's perfect for formal occasions, business meetings, or any setting where a statement of refined taste is desired.	2026-03-22 03:46:26.675606+00
16	90	The Royal Oak Concept 26650FO.OO.D353CA.01 embodies Audemars Piguet's commitment to pushing the boundaries of haute horlogerie. It exemplifies their dedication to technical innovation and audacious design, cementing its place as a landmark piece in modern watchmaking history.	This exclusive timepiece is highly sought after by serious collectors who appreciate Audemars Piguet's avant-garde spirit. Its limited production run and innovative design contribute to its strong resale value and often result in lengthy waitlists.	The 26650FO.OO.D353CA.01 features a striking, angular case crafted from forged carbon, juxtaposed with a vibrant green dial that accentuates the openworked movement. Electric blue accents add a touch of futuristic flair, while meticulous finishing details elevate its aesthetic impact.	This bold statement piece is ideal for individuals who embrace unconventional style and appreciate horological excellence. Its robust design and 70-hour power reserve make it suitable for both formal occasions and adventurous pursuits.	2026-03-22 03:46:45.949193+00
17	69	The Royal Oak Offshore has always been a statement piece, pushing the boundaries of luxury sports watches. The 15605SK.OO.A350CA.01 refines this legacy, proving that Audemars Piguet can deliver both bold presence and understated elegance.	This reference appeals to collectors seeking a versatile Offshore without sacrificing the iconic design elements. Its relative accessibility compared to other limited-edition models makes it a desirable piece for both seasoned enthusiasts and newcomers to the brand.	The 15605SK.OO.A350CA.01 blends the robust lines of the Offshore with a more streamlined profile, achieved through its 42mm case size and khaki green dial. The black ceramic accents add a touch of contemporary sophistication while maintaining the collection's signature sporty aesthetic.	This watch is ideal for individuals who appreciate both style and functionality. Its versatility makes it suitable for everyday wear, business meetings, or weekend adventures. It pairs well with casual attire as well as more refined ensembles.	2026-03-22 03:47:04.960478+00
18	266	The Classique 7337 embodies Breguet's enduring legacy of marrying horological innovation with timeless elegance. It represents the pinnacle of complication integration within a classic design language, a testament to the brand's mastery over centuries.	This timepiece is highly sought after by seasoned collectors drawn to its exquisite craftsmanship and Breguet's prestigious heritage. Its limited production and enduring desirability often result in waitlists and strong resale value.	The Classique 7337 features a refined silver dial with delicate guilloché patterns, punctuated by clear, legible Arabic numerals and blued-steel hands. The moon phase aperture adds a touch of celestial poetry, while the case proportions are perfectly balanced for both formal and casual wear.	This watch is ideal for discerning individuals who appreciate understated luxury and intricate horological details. Its versatility makes it suitable for evening events, business meetings, or even everyday wear on special occasions.	2026-03-22 03:47:21.295877+00
19	273	The Marine Chronographe 5527 embodies Breguet's enduring legacy of maritime inspiration, seamlessly blending historical significance with modern horological advancements. It represents the brand's commitment to pushing boundaries while remaining true to its heritage.	This timepiece is highly sought after by collectors drawn to Breguet's exceptional craftsmanship and iconic Marine collection. Its limited production and prestigious status ensure strong resale value, often commanding a premium in the secondary market.	The 5527 features a dynamic chronograph layout integrated within a refined aesthetic. The blue dial evokes the depths of the sea, while maritime-inspired detailing like the guilloché pattern and blued hands pay homage to Breguet's nautical roots. The titanium case offers both durability and contemporary elegance.	This watch is ideal for discerning individuals who appreciate both horological excellence and a touch of adventure. Its versatility makes it suitable for formal occasions, weekend excursions, or everyday wear, complementing a variety of styles.	2026-03-22 03:47:38.578242+00
20	278	The Tradition collection embodies Breguet's dedication to horological heritage, marrying modern complications with the aesthetic principles of Abraham-Louis Breguet. The 7035, with its retrograde seconds display, elevates this lineage by showcasing both technical prowess and artistic sensibility.	Highly sought after by collectors drawn to Breguet's legacy and intricate craftsmanship, the Tradition line commands a premium in the secondary market. Limited production runs and waiting lists contribute to its exclusivity.	The 7035 embodies Breguet's signature architectural dial design, with exposed bridges and gears juxtaposed against a refined white mother-of-pearl dial. The yellow gold case, accented by blue enamel details, adds a touch of opulence while maintaining the collection's understated elegance.	This timepiece is ideal for discerning individuals who appreciate both horological complexity and timeless aesthetics. It complements formal attire and special occasions, adding a touch of sophistication to any ensemble.	2026-03-22 03:47:55.615285+00
21	197	The Astronomic Souveraine represents the pinnacle of F.P. Journe's commitment to horological excellence, showcasing the brand's mastery of complex complications within a harmonious design. It elevates independent watchmaking by demonstrating the potential for both technical sophistication and aesthetic refinement.	This exclusive timepiece is highly sought after by discerning collectors who appreciate rare and intricate watches. Its limited production and prestigious status ensure strong resale value and often result in lengthy waitlists.	The Astronomic Souveraine embodies F.P. Journe's signature aesthetic: a blend of classic elegance and modern innovation. The silver dial features a meticulously crafted arrangement of subdials, while the 44mm rose gold case exudes timeless sophistication. Each detail, from the polished surfaces to the blued steel hands, reflects meticulous craftsmanship.	This grand complication watch is ideal for collectors and enthusiasts who value horological artistry and appreciate a statement piece. Its size and presence make it suitable for formal occasions and those who desire a timepiece that commands attention.	2026-03-22 03:48:14.026981+00
22	200	The Élégante collection exemplifies F.P. Journe's mastery of contemporary design while respecting horological tradition. This reference, with its titanium case and subtle diamond accents, demonstrates the brand's ability to seamlessly blend technical prowess with understated elegance.	This timepiece appeals to discerning collectors who appreciate both fine watchmaking and exquisite jewellery. Its limited production and high demand often result in waitlists, making it a highly sought-after piece on the secondary market.	The Élégante 40 mm Titanium 2 rows of diamonds features a distinctive tonneau case that exudes modern sophistication. The minimalist grey dial with its clean lines and applied numerals creates a sense of refined simplicity, while the two rows of meticulously set diamonds add a touch of feminine allure.	This watch is ideal for individuals who seek a timepiece that effortlessly transitions from daytime elegance to evening glamour. Its versatility makes it perfect for both formal occasions and everyday wear, complementing a range of styles.	2026-03-22 03:48:31.182341+00
23	163	Glashütte Original's Senator Excellence Panorama Date Moon Phase embodies the brand's dedication to traditional German watchmaking, seamlessly blending horological precision with elegant aesthetics. It represents a pinnacle of craftsmanship within a respected lineage.	This timepiece appeals to discerning collectors who appreciate both historical significance and contemporary design. Its limited production and exceptional quality contribute to its strong resale value and often result in waitlists.	The Senator Excellence's visual DNA is defined by classic proportions, a clean dial layout, and meticulous finishing. The frosted silver dial adds a touch of modernity, while the Panorama Date and moon phase display maintain a harmonious balance with the overall design.	This watch is ideal for individuals who seek an elegant timepiece suitable for both formal occasions and everyday wear. Its 40mm case size complements various wrist sizes, and its timeless design pairs effortlessly with a range of attire.	2026-03-22 03:48:47.178655+00
24	102	The Duomètre collection represents Jaeger-LeCoultre's dedication to pushing the boundaries of horological innovation. The Q6012421 exemplifies this with its unique dual-wing architecture, a testament to the brand's mastery of complex movements.	This timepiece appeals to discerning collectors seeking both mechanical ingenuity and aesthetic refinement. Its limited production and prestigious heritage ensure strong resale value and potential for future appreciation.	The Q6012421 features a harmonious blend of classic elegance and modern sophistication. The 40.5mm pink gold case, silver dial with subtle detailing, and refined hands create a timeless aesthetic that exudes understated luxury.	This watch is ideal for the individual who appreciates horological excellence and seeks a timepiece that transcends trends. It complements formal attire and adds an air of sophistication to special occasions.	2026-03-22 03:49:03.949273+00
25	170	The PanoLunarTourbillon represents Glashütte Original's commitment to both traditional horological excellence and modern design sensibilities. It showcases the brand's mastery of complex complications while pushing the boundaries of aesthetic refinement within its established collection.	This watch appeals to discerning collectors seeking a unique blend of technical sophistication and understated elegance. Its limited production run and platinum case contribute to its desirability, making it a highly sought-after piece with strong resale potential.	The PanoLunarTourbillon 1-93-03-01-03-64 features a contemporary interpretation of Glashütte Original's signature asymmetrical dial layout. The galvanic rose 'Iron Ore' dial provides a rich backdrop for the open tourbillon and moon phase display, while the platinum case exudes timeless sophistication.	This timepiece is ideal for formal occasions and everyday wear by individuals who appreciate refined horology. Its 40mm diameter suits a variety of wrist sizes, and its versatility allows it to be paired with both classic and contemporary attire.	2026-03-22 03:49:21.80856+00
26	115	The Master Ultra Thin MOON Q1368430 embodies Jaeger-LeCoultre's mastery of understated elegance. It represents the pinnacle of classic complication design, seamlessly integrating a moon phase display into a timeless silhouette without sacrificing legibility or refinement.	This timepiece appeals to discerning collectors seeking both horological excellence and wearable sophistication. Its limited production and enduring desirability contribute to its strong resale value, often commanding premiums in the secondary market.	The Master Ultra Thin MOON Q1368430 features a harmonious blend of classic proportions and contemporary detailing. The 39mm stainless steel case exudes understated masculinity, while the silvered grey dial with its subtle moon phase aperture creates an aura of refined elegance.	This watch is ideal for individuals who appreciate timeless design and sophisticated complications. It complements formal attire as well as smart casual ensembles, making it a versatile choice for both day and evening occasions.	2026-03-22 03:49:37.979597+00
27	210	The Hand Made 1 embodies Greubel Forsey's unwavering commitment to artisanal watchmaking, reviving a nearly forgotten craft where precision and artistry intertwine. It represents a defiant stance against mass production, celebrating the enduring value of human skill in an increasingly automated world.	This timepiece is coveted by discerning collectors who appreciate the pinnacle of horological craftsmanship and exclusivity. Its limited availability and unparalleled hand-finishing ensure its position as a prized asset with strong resale potential.	The Hand Made 1 exudes understated elegance through its classic white gold case, refined silver dial, and meticulously crafted details. The proportions are balanced and timeless, while the finishing touches speak to the meticulous attention paid to every aspect of its creation.	This watch is ideal for individuals who value heritage, artistry, and exceptional quality. It complements formal occasions, sophisticated gatherings, and those who appreciate a timepiece that transcends mere functionality.	2026-03-22 03:49:56.052604+00
28	261	The Double Balancier Convexe embodies Greubel Forsey's relentless pursuit of horological innovation, pushing the boundaries of watchmaking with its groundbreaking double balance wheel system. It represents a pinnacle of technical mastery and artistic vision, solidifying the brand's position as a leader in haute horlogerie.	This piece is highly sought after by serious collectors drawn to Greubel Forsey's exceptional craftsmanship and avant-garde designs. Its limited production and prestigious status ensure strong resale value and often result in lengthy waitlists.	The Double Balancier Convexe features a striking openworked dial that showcases the intricate mechanics of its double balance wheel system, creating a captivating interplay of form and function. The titanium case, with its sculpted lines and polished surfaces, exudes both robustness and elegance.	This timepiece is ideal for discerning individuals who appreciate horological excellence and bold aesthetics. Its dynamic design and exceptional power reserve make it perfect for formal occasions and everyday wear alike.	2026-03-22 03:50:12.806166+00
29	338	The Classics Index Automatic embodies Frederique Constant's commitment to accessible luxury, proving that impeccable Swiss craftsmanship needn't be prohibitively expensive. It represents a bridge between traditional horological values and modern sensibilities.	This timepiece appeals to collectors seeking understated elegance and reliable performance. Its enduring design and consistent quality contribute to its strong resale value, making it a coveted piece for enthusiasts.	The Classics Index Automatic adheres to Frederique Constant's signature clean lines and refined proportions. The silver dial features minimalist indices and hands, while the 40mm stainless steel case exudes timeless sophistication.	This versatile watch is perfect for everyday wear, effortlessly complementing both formal attire and casual ensembles. Its balanced size suits a variety of wrist sizes and pairs well with leather or metal straps.	2026-03-22 03:50:25.067525+00
30	354	The Manufacture Worldtimer embodies Frederique Constant's commitment to in-house complications and accessible luxury. It demonstrates the brand's ability to create sophisticated timepieces with a user-friendly approach to complex functions.	Collectors drawn to both technical prowess and elegant aesthetics find resonance in this piece. Its market position is strong, with limited production runs contributing to its desirability and potential for appreciation.	The Worldtimer's design language is characterized by clean lines, a legible blue dial punctuated by contrasting city markers, and a 42mm case that strikes a balance between presence and wearability. The finishing details, such as the polished bezel and brushed surfaces, exude refinement.	The Worldtimer is ideal for the discerning traveler who appreciates both functionality and style. Its intuitive world-time display simplifies navigating different time zones, making it perfect for business trips or leisurely adventures.	2026-03-22 03:50:38.724733+00
31	347	The Slimline Perpetual Calendar Manufacture FC-775V4S4 embodies Frederique Constant's commitment to accessible haute horlogerie. It demonstrates the brand's mastery of in-house complications, proving that sophistication needn't be shrouded in complexity.	This timepiece appeals to discerning collectors seeking a balance between elegance and functionality. Its limited production run and inherent desirability contribute to its strong resale value.	The FC-775V4S4 embodies understated luxury with its sleek, minimalist design. The silver dial features clear, legible Arabic numerals and refined subdials, while the 42mm stainless steel case exudes a timeless sophistication.	This watch is ideal for individuals who appreciate refined horology without ostentation. It complements formal attire and adds a touch of understated elegance to everyday wear.	2026-03-22 03:50:53.911919+00
32	245	The GMT-Master II 'Pepsi' embodies Rolex's enduring legacy in travel timekeeping. Its evolution from a tool for pilots to a global icon reflects the brand's ability to fuse functionality with aspirational design, influencing generations of watchmakers.	Highly coveted by both seasoned collectors and newcomers, the GMT-Master II 'Pepsi' commands premium prices on the secondary market. Its enduring popularity ensures strong resale value and often involves lengthy waitlists or pre-orders.	The M126710BLRO-0002 blends classic Rolex DNA with contemporary refinement. The iconic red and blue bezel, a nod to its aviation heritage, contrasts beautifully against the black dial. Its 40mm Oystersteel case and Jubilee bracelet offer a sporty yet elegant profile.	This timepiece is perfect for globetrotters, adventurers, and those who appreciate both style and substance. It effortlessly complements casual attire while adding a touch of sophistication to semi-formal occasions.	2026-03-22 03:51:11.36003+00
33	235	The Daytona in yellow gold is a testament to Rolex's ability to balance heritage and innovation. It honors the model's racing legacy while embracing a more opulent aesthetic that resonates with contemporary collectors seeking both performance and prestige.	This reference sits firmly within the realm of high-luxury collecting, attracting seasoned enthusiasts drawn to its exclusivity and timeless appeal. The Daytona's enduring popularity ensures strong resale value, often commanding premiums in the secondary market.	The M126503-0001 embodies a striking visual dichotomy: the warm glow of yellow gold juxtaposed against the stark black dial creates a captivating contrast. Proportions are classic Daytona, with a 40mm case that sits comfortably on most wrists.	This watch is ideal for individuals who appreciate both refined elegance and sporting prowess. It elevates formal attire while seamlessly transitioning to more casual settings, making it a versatile companion for discerning collectors.	2026-03-22 03:51:28.015645+00
34	98	The Polaris Q9068670 exemplifies Jaeger-LeCoultre's commitment to marrying robust functionality with refined aesthetics, a hallmark of their enduring legacy in the luxury sports watch segment.	This timepiece will resonate with collectors seeking a versatile and sophisticated sports watch. Its limited production run and desirable specifications contribute to its strong resale value and potential for future appreciation.	The Q9068670 boasts a harmonious blend of vintage-inspired cues and contemporary design elements. The 42mm stainless steel case, punctuated by contrasting green dial accents and polished finishing details, exudes both ruggedness and elegance.	This watch is ideally suited for discerning individuals who value both style and performance. It complements a range of lifestyles, from weekend adventures to sophisticated evening events.	2026-03-22 03:51:42.387479+00
35	360	Frederique Constant elevates its renowned Worldtimer complication with this Highlife iteration, demonstrating a commitment to both heritage and modern design language within the accessible luxury segment.	This watch appeals to collectors seeking contemporary dress watches with practical complications. Its limited production run and growing brand recognition contribute to its desirability on the secondary market.	The Highlife Worldtimer embodies a blend of classic elegance and modern dynamism. The integrated bracelet provides a sleek, sporty silhouette while the blue dial's intuitive worldtime display maintains Frederique Constant's signature readability.	This timepiece is ideal for discerning individuals who appreciate both style and functionality. It seamlessly transitions from boardroom meetings to evening soirées, complementing formal attire with its sophisticated design.	2026-03-22 03:51:55.504973+00
36	91	The Reverso Duoface Tourbillon Q3926480 exemplifies Jaeger-LeCoultre's mastery of both aesthetics and horological innovation. It honors the brand's rich history while pushing the boundaries of watchmaking with its intricate tourbillon mechanism and reversible design, a testament to their enduring legacy.	This timepiece is highly coveted by collectors seeking rare and complex pieces with historical significance. Its limited production and prestigious heritage ensure strong resale value and often result in lengthy waitlists.	The Duoface Tourbillon Q3926480 embodies Art Deco elegance with its rectangular pink gold case and contrasting silver and black dials. The tourbillon cage, visible on one face, adds a dynamic element to the classic design, creating a captivating interplay of form and function.	This watch is perfect for discerning collectors who appreciate intricate complications and timeless design. Its versatility allows it to be worn on both formal and semi-formal occasions, complementing elegant attire and showcasing its exquisite craftsmanship.	2026-03-22 03:52:13.372909+00
37	284	The Reine de Naples 8918 embodies Breguet's legacy as a pioneer in wristwatch design, tracing its lineage back to the iconic first timepiece created for Queen Caroline Murat. It represents the brand's enduring commitment to feminine elegance and horological innovation.	This piece is highly coveted by collectors seeking exquisite craftsmanship and historical significance within the realm of luxury women's watches. Its limited production and Breguet's esteemed reputation ensure strong resale value and potential for future appreciation.	The Reine de Naples 8918 exudes a captivating blend of classicism and modernity. The ovoid case, reminiscent of vintage pocket watches, is adorned with delicate gem-setting, while the black dial features an off-center chapter ring and elegant Breguet numerals for a distinctly feminine aesthetic.	This timepiece is ideal for discerning women who appreciate timeless elegance and exceptional horological artistry. It complements formal attire and special occasions, adding a touch of sophistication to any ensemble.	2026-03-22 03:52:31.112814+00
38	306	The Constellation collection embodies Omega's enduring commitment to precision and elegance. This particular reference reinterprets the iconic clawed case for a contemporary audience, bridging the gap between horological heritage and modern aesthetics.	This model appeals to collectors seeking a versatile timepiece with both classic appeal and contemporary flair. Its smaller size and feminine design make it highly desirable within the luxury watch market, often commanding premium prices on the secondary market.	The Constellation 29 mm features a harmonious blend of polished stainless steel and warm 18K Sedna gold accents, creating a luxurious and sophisticated aesthetic. The white mother-of-pearl dial radiates elegance, while the prominent claws remain a signature design element.	This watch is perfect for discerning individuals who appreciate refined style and timeless elegance. It complements both formal attire and everyday ensembles, making it ideal for special occasions or as an everyday statement piece.	2026-03-22 03:52:47.005183+00
39	296	The Seamaster Diver 300M embodies Omega's enduring legacy in professional diving watches. It represents a pinnacle of technical prowess and aesthetic refinement, bridging the gap between vintage heritage and contemporary functionality.	Highly sought-after by both seasoned collectors and newcomers to luxury timepieces, the Diver 300M enjoys strong resale value due to its iconic status and consistent demand. Its versatility ensures a place in diverse collections, making it a timeless investment.	The watch features a robust stainless steel case with refined proportions, complemented by a black ceramic bezel that showcases Omega's signature wave-pattern texture. The dial is a study in legibility, featuring luminous hour markers and hands against a backdrop of deep black, while the helium escape valve adds a touch of technical sophistication.	This timepiece is ideal for individuals who appreciate both style and substance. Its sporty character makes it perfect for active lifestyles, while its refined design elevates any ensemble. It's equally at home on a weekend adventure or during a sophisticated evening affair.	2026-03-22 03:53:05.183994+00
40	294	A testament to Omega's commitment to innovation, the Super Racing showcases their groundbreaking Spirate regulation system, pushing the boundaries of chronometric accuracy within a storied lineage. It represents a new era for the Speedmaster, blending heritage with cutting-edge technology.	Highly sought after by serious collectors drawn to its technical prowess and limited availability. Its modern design and performance characteristics position it as a future classic, likely commanding strong resale value.	The Super Racing embodies a bold, contemporary aesthetic with its expansive 44.25mm stainless steel case, black dial punctuated by vibrant yellow accents, and purposeful chronograph layout. The finishing details exude quality, from the polished bezel to the meticulously engraved subdials.	This watch is ideal for individuals who appreciate both technical sophistication and timeless design. Its robust presence suits active lifestyles and complements formal attire with equal ease.	2026-03-22 03:53:20.190069+00
41	308	The De Ville Prestige embodies Omega's enduring commitment to timeless elegance, upholding a legacy of refined horological craftsmanship that dates back to the brand's early 20th-century dress watches. It represents a return to essential watchmaking values, prioritizing understated sophistication over flashy complications.	A coveted piece among discerning collectors seeking classic Omega designs with enduring market value. Its limited production and growing popularity contribute to its desirability, often resulting in waitlists for specific references.	The De Ville Prestige exudes restrained elegance through its symmetrical dial featuring Roman numerals, slender hands, and a minimalist date window at 6 o'clock. The polished stainless steel case, measuring a versatile 40mm, complements the understated grey dial, creating a harmonious balance of form and function.	This watch is ideal for individuals who appreciate timeless style and refined aesthetics. Its versatility makes it suitable for both formal occasions and everyday wear, pairing seamlessly with tailored suits or casual attire.	2026-03-22 03:54:02.218234+00
42	12	The Patek Philippe 5327G-001 embodies the pinnacle of traditional Swiss watchmaking. Its perpetual calendar complication is a testament to horological mastery, while its classic design language reinforces Patek Philippe's legacy as a purveyor of enduring elegance.	Highly sought after by seasoned collectors and connoisseurs, the 5327G-001 commands a premium price due to its limited production and impeccable pedigree. Its resale value remains strong, reflecting its status as an investment piece.	The 5327G-001's aesthetic is defined by understated sophistication. The white gold case, measuring a refined 39mm, complements the blue dial perfectly. A meticulously arranged perpetual calendar display ensures legibility without compromising the watch's elegant simplicity.	This timepiece is ideal for discerning individuals who appreciate classic horology and timeless style. It elevates formal occasions and adds a touch of understated luxury to everyday wear.	2026-03-22 03:54:16.925183+00
43	2	The Nautilus 5811/1G represents a pivotal moment in Patek Philippe's history, marking the transition from steel to precious metal for this iconic sports watch. It signifies the brand's commitment to evolution while honoring its heritage, solidifying the Nautilus's status as a modern classic.	The 5811/1G is highly sought after by collectors seeking exclusivity and prestige. Its limited production and white gold construction elevate it above its steel predecessor, commanding premium prices on the secondary market. Long waitlists and strong demand attest to its enduring allure.	The 5811/1G embodies a timeless design language with its signature porthole-inspired case, horizontal embossing, and integrated bracelet. The white gold case adds a touch of understated elegance, while the deep blue sunburst dial exudes sophistication and depth.	This watch is ideal for discerning individuals who appreciate both luxury and functionality. Its versatile design complements formal attire as well as casual ensembles, making it perfect for evening events, business meetings, or weekend getaways.	2026-03-22 03:54:32.692487+00
44	4	The Calatrava collection represents Patek Philippe's commitment to timeless elegance and horological precision. The 4997/200G-001 embodies this legacy, seamlessly blending the classic design codes of the Calatrava with contemporary embellishments.	This watch appeals to discerning collectors who appreciate both heritage and modern luxury. Its limited production run and combination of precious materials contribute to its desirability on the secondary market.	The 4997/200G-001 features a classic Calatrava silhouette with refined proportions, a sunburst midnight blue dial that evokes depth and sophistication, and a white gold case adorned with diamonds for a touch of feminine sparkle.	This timepiece is perfect for evening events, formal occasions, or any setting where understated elegance is desired. Its versatility extends to various wrist sizes and complements both classic and contemporary attire.	2026-03-22 03:54:46.828871+00
45	13	The Patek Philippe Aquanaut Luce Haute Joaillerie embodies the pinnacle of horological artistry, seamlessly blending Patek's revered watchmaking heritage with exceptional jewellery craftsmanship. It represents a rare convergence of technical precision and aesthetic brilliance, pushing the boundaries of luxury timepieces.	This exclusive piece is coveted by discerning collectors seeking unparalleled rarity and prestige. Its limited production run and exquisite design ensure strong resale value and often result in significant waitlists. The Aquanaut Luce Haute Joaillerie is a statement piece for those who appreciate the finest expressions of luxury.	The 5268/461G-001 features a white gold case with refined proportions, adorned with a mesmerizing dial set with diamonds and blue sapphires. The interplay of light and color creates a captivating visual experience, while retaining the Aquanaut's signature modern elegance.	This timepiece is ideal for formal occasions, galas, or any event where its dazzling presence will command attention. It complements sophisticated evening attire and exudes an aura of timeless luxury. The 38.8mm case size suits a variety of wrist sizes.	2026-03-22 03:55:03.687289+00
46	138	The Datograph 403.031 embodies A. Lange & Söhne's commitment to horological excellence, showcasing the pinnacle of German watchmaking tradition with its intricate movement and meticulous finishing. It stands as a testament to the brand's legacy of precision and innovation.	Highly sought-after by serious collectors, the Datograph 403.031 commands premium prices on the secondary market due to its limited production and enduring popularity. Its status as a modern classic ensures strong resale value and often involves waiting lists for new acquisitions.	The Datograph 403.031 exudes timeless elegance with its warm rose-gold case, contrasting beautifully with the solid silver dial. The iconic Lange architecture features perfectly balanced subdials, a prominent outsize date, and elegant blued steel hands, creating a harmonious and visually captivating composition.	This watch is ideal for discerning individuals who appreciate fine craftsmanship and timeless design. It complements formal occasions, evening attire, and sophisticated lifestyles. Its 39mm case size suits a range of wrist sizes.	2026-03-22 03:55:19.763547+00
47	174	The SeaQ Chronograph represents Glashütte Original's commitment to marrying historical diving watch aesthetics with modern technical prowess. It embodies the brand's dedication to both precision engineering and a distinct design language rooted in its German heritage.	This chronograph appeals to collectors seeking a unique blend of vintage charm and contemporary flair. Its limited production run and vibrant colourway contribute to its desirability, making it a sought-after piece within the Glashütte Original ecosystem.	The SeaQ Chronograph's design language is characterized by bold, legible numerals against a silver screen dial, reminiscent of vintage diving instruments. The 43.2mm stainless steel case wears comfortably while maintaining a robust presence, and finishing details like the polished bezel add a touch of refinement.	This chronograph is ideal for individuals who appreciate both style and functionality. Its versatility extends to various occasions, from casual outings to dressier events, and pairs well with a range of attire.	2026-03-22 03:55:34.195745+00
\.


--
-- Data for Name: WatchEditorialLinks; Type: TABLE DATA; Schema: public; Owner: tourbillon
--

COPY public."WatchEditorialLinks" ("WatchId", "EditorialContentId") FROM stdin;
32	1
35	1
36	1
37	1
38	1
39	1
40	1
228	2
229	2
230	2
231	2
232	2
227	3
238	3
239	3
240	3
241	3
313	4
314	4
315	4
316	4
317	4
318	4
319	4
320	4
34	5
56	5
363	5
364	5
247	6
248	6
249	6
250	6
251	6
321	7
322	7
323	7
324	7
325	7
326	7
327	7
33	8
49	8
50	8
51	8
52	8
53	8
54	8
55	8
328	9
329	9
330	9
331	9
332	9
133	10
139	10
140	10
147	10
148	10
149	10
150	10
132	11
141	11
143	11
144	11
145	11
155	11
134	12
135	12
146	12
156	12
157	12
158	12
255	13
256	13
257	13
258	13
41	14
42	14
43	14
44	14
45	14
46	14
47	14
48	14
57	15
58	15
60	15
73	15
74	15
75	15
76	15
77	15
78	15
79	15
80	15
81	15
82	15
83	15
84	15
85	15
59	16
72	16
87	16
88	16
89	16
90	16
61	17
62	17
63	17
64	17
65	17
66	17
67	17
68	17
69	17
70	17
71	17
86	17
263	18
264	18
265	18
266	18
267	18
268	18
269	18
270	18
271	18
272	19
273	19
274	19
275	19
276	19
277	20
278	20
279	20
280	20
281	20
282	20
283	20
184	21
185	21
186	21
187	21
188	21
189	21
190	21
191	21
192	21
193	21
194	21
195	21
196	21
197	21
198	22
199	22
200	22
201	22
202	22
254	22
159	23
160	23
161	23
162	23
163	23
164	23
165	23
96	24
102	24
103	24
104	24
110	24
111	24
112	24
113	24
166	25
167	25
168	25
169	25
170	25
171	25
172	25
176	25
177	25
178	25
114	26
115	26
116	26
117	26
118	26
119	26
120	26
121	26
122	26
123	26
124	26
125	26
126	26
127	26
128	26
129	26
130	26
131	26
208	27
209	27
210	27
211	27
212	27
213	27
214	27
203	28
204	28
205	28
206	28
207	28
259	28
260	28
261	28
262	28
338	29
339	29
340	29
341	29
342	29
343	29
344	29
352	30
353	30
354	30
355	30
356	30
357	30
345	31
346	31
347	31
348	31
349	31
350	31
351	31
242	32
243	32
244	32
245	32
246	32
233	33
234	33
235	33
236	33
237	33
93	34
97	34
98	34
99	34
105	34
106	34
107	34
108	34
109	34
253	35
358	35
359	35
360	35
361	35
362	35
91	36
92	36
94	36
95	36
100	36
101	36
284	37
285	37
287	37
303	38
304	38
305	38
306	38
307	38
296	39
297	39
298	39
299	39
300	39
301	39
302	39
252	40
288	40
289	40
290	40
291	40
292	40
293	40
294	40
295	40
308	41
309	41
310	41
311	41
312	41
3	42
12	42
14	42
16	42
17	42
19	42
21	42
2	43
8	43
9	43
10	43
11	43
1	44
4	44
5	44
6	44
7	44
22	44
23	44
24	44
25	44
26	44
27	44
28	44
29	44
30	44
31	44
13	45
15	45
18	45
20	45
136	46
137	46
138	46
142	46
151	46
152	46
153	46
154	46
173	47
174	47
175	47
179	47
180	47
181	47
182	47
183	47
\.


--
-- Name: WatchEditorialContents_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: tourbillon
--

SELECT pg_catalog.setval('public."WatchEditorialContents_Id_seq"', 47, true);


--
-- Name: WatchEditorialContents PK_WatchEditorialContents; Type: CONSTRAINT; Schema: public; Owner: tourbillon
--

ALTER TABLE ONLY public."WatchEditorialContents"
    ADD CONSTRAINT "PK_WatchEditorialContents" PRIMARY KEY ("Id");


--
-- Name: WatchEditorialLinks PK_WatchEditorialLinks; Type: CONSTRAINT; Schema: public; Owner: tourbillon
--

ALTER TABLE ONLY public."WatchEditorialLinks"
    ADD CONSTRAINT "PK_WatchEditorialLinks" PRIMARY KEY ("WatchId");


--
-- Name: IX_WatchEditorialContents_SeedWatchId; Type: INDEX; Schema: public; Owner: tourbillon
--

CREATE INDEX "IX_WatchEditorialContents_SeedWatchId" ON public."WatchEditorialContents" USING btree ("SeedWatchId");


--
-- Name: IX_WatchEditorialLinks_EditorialContentId; Type: INDEX; Schema: public; Owner: tourbillon
--

CREATE INDEX "IX_WatchEditorialLinks_EditorialContentId" ON public."WatchEditorialLinks" USING btree ("EditorialContentId");


--
-- Name: WatchEditorialContents FK_WatchEditorialContents_Watches_SeedWatchId; Type: FK CONSTRAINT; Schema: public; Owner: tourbillon
--

ALTER TABLE ONLY public."WatchEditorialContents"
    ADD CONSTRAINT "FK_WatchEditorialContents_Watches_SeedWatchId" FOREIGN KEY ("SeedWatchId") REFERENCES public."Watches"("Id") ON DELETE CASCADE;


--
-- Name: WatchEditorialLinks FK_WatchEditorialLinks_WatchEditorialContents_EditorialContent~; Type: FK CONSTRAINT; Schema: public; Owner: tourbillon
--

ALTER TABLE ONLY public."WatchEditorialLinks"
    ADD CONSTRAINT "FK_WatchEditorialLinks_WatchEditorialContents_EditorialContent~" FOREIGN KEY ("EditorialContentId") REFERENCES public."WatchEditorialContents"("Id") ON DELETE CASCADE;


--
-- Name: WatchEditorialLinks FK_WatchEditorialLinks_Watches_WatchId; Type: FK CONSTRAINT; Schema: public; Owner: tourbillon
--

ALTER TABLE ONLY public."WatchEditorialLinks"
    ADD CONSTRAINT "FK_WatchEditorialLinks_Watches_WatchId" FOREIGN KEY ("WatchId") REFERENCES public."Watches"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict Ej7hikzplgFmFrzt604ilrSIClnxttPim3geSQng8xbPBirYTpE0lhysdvp7Ixo

